on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
    
    - name: Modify .env file
      run: |
        sed -i "s|APP_KEY=.*|APP_KEY=base64:Tpu47xSQ0OJ1mDC+NkI+cB5rc9ot2FqXogYYtx2eSJc=|" .env
        sed -i "s|APP_ENV=.*|APP_ENV=production|" .env
        sed -i "s|APP_URL=.*|APP_URL=http://educore.kesug.com|" .env
        sed -i "s|DB_HOST=.*|DB_HOST=${{ secrets.DB_HOST }}|" .env
        sed -i "s|DB_PORT=.*|DB_PORT=3306|" .env
        sed -i "s|DB_DATABASE=.*|DB_DATABASE=${{ secrets.DB_DATABASE }}|" .env
        sed -i "s|DB_USERNAME=.*|DB_USERNAME=${{ secrets.DB_USERNAME }}|" .env
        sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=${{ secrets.DB_PASSWORD }}|" .env

    # - name: Require laravel/views
    #   run: composer require laravel/views
    
    # - name: Install Composer dependencies
    #   run: composer install --no-interaction --optimize-autoloader

    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '21.6.0'

    # - name: Install Node.js dependencies
    #   run: npm install
      
    # - name: Build frontend assets
    #   run: npm run build

    # - name: Cache config/routes/views
    #   run: |
    #     php artisan config:cache
    #     php artisan view:cache

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/
        # git-ftp-args: --syncroot ./ --state-file ./.github/ftp-deploy-sync-state.json